### ISSUE TITLE
Publish Firefox version?

### ISSUE THREAD

**Issue by matsest** [merill/refined-microsoft-learn#1]
Thanks for creating this simple, yet useful extension @merill!

Re the comment in https://github.com/merill/refined-microsoft-learn#firefox-support:

The firefox version works fine - tested locally following https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#trying_it_out

The only thing needed for the user (as [per use](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions) of Firefox extensions) is to allow the extension to run on the specified domain.

Loaded temporarily (follows guide linked above):

![image](https://github.com/merill/refined-microsoft-learn/assets/10927304/7e3a7d0b-b0a8-46c5-846f-d574f7a69d25)

Before allow:

![image](https://github.com/merill/refined-microsoft-learn/assets/10927304/0c4b0bbe-6db6-4d52-8fbf-525d10cd33d0)

After allow:

![image](https://github.com/merill/refined-microsoft-learn/assets/10927304/bb797da4-631d-4632-b817-59d135eec387)

**Comment by merill** [comment]
Nice. Thanks for testing.

**Comment by LioDiera** [comment]
Just tested the same way by loading it temporarily and it works just fine! Please publish.

**Comment by merill** [comment]
I've just submitted the Firefox version for review. Will post once it's approved.

The good news is we have options to toggle as well.

**Comment by merill** [comment]
See https://addons.mozilla.org/en-US/firefox/addon/refined-microsoft-learn/
