### ISSUE TITLE
[IDEA]: TOC to the right

### ISSUE THREAD

**Issue by aloneguid** [merill/refined-microsoft-learn#2]
Would it be possible to request a feature - move TOC to the right, where we have spam at the moment? I'm pretty sure a few years back this is how it used to be:

![image](https://github.com/merill/refined-microsoft-learn/assets/3155189/9b5e70d8-a952-4eb5-b8f7-24c1091be98f)

**Comment by merill** [comment]
That's a good idea. Will probably need to add it as an option that can be turned on/off

**Comment by aloneguid** [comment]
@merill i've added options to run off/on and TOC in #3. Sorry, couldn't wait as I need it myself ;)

**Comment by merill** [comment]
Amazing work. @aloneguid 🥰

I've submitted a new version of the extension with your updates to the Chrome, Edge and Firefox stores!
